---
title: "Potakast"
baseURL: "https://potakast.takashi.dev/"
theme: "zen"
languageCode: "ja-JP"
defaultContentLanguage: "jp"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 100
author:
  name: "Takashi Kato"
  url: "https://potakast.takashi.dev/about"
  avatar: "path/to/some-image.jpg"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "info@example.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "A podcast by Takashi Kato."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  logo: false
  mobileMenu: true
  poweredby: false
  sidebar: true
  submitted: false

  podcast:
    title:        "Potakast"
    description:  "Potakastは、ITエンジニアのTakaが、世界や日常のいたるところに散らばっている楽しいも物、美しいもの、不思議なものをお話ししていきます。"
    image":       "https://www.takashi.dev/images/20200920-ios14_home.jpg"
    category:
      name:       "Society & Culture"
    author:       "Taka"
    owner:
      name:       "Takashi Kato"
    local:        false